application:
  config:
    premium-billing-url: http://localhost:7092/api/v1/premium-billing
  user-info:
    user-id: X-USER-ID
    username: X-USER-NAME
    service-id: X-SERVICE-ID
    account-type: X-ACCOUNT-TYPE
spring:
  application:
    name: member-management
  data:
    mongodb:
      username: membermanagementadmin
      password: password
      host: localhost
      port: 27019
      database: member-management
      authentication-database: member-management
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
management:
  server:
    port: 9002